language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - nightly
  - hhvm
  - hhvm-nightly

env:
  global:
    - SYMFONY_ENV=test
    - SYMFONY__TEST_DATABASE_NAME=clastic_test
    - SYMFONY__TEST_DATABASE_USER=travis
    - SYMFONY__TEST_DATABASE_PASSWORD=""

before_script:
  - mysql -e 'create database clastic_test;'
  - composer self-update
  - composer install --prefer-source --no-interaction
  - php ./app/console assets:install
  - php ./app/console doctrine:schema:drop --force
  - php ./app/console doctrine:schema:create
  - php ./app/console doctrine:fixtures:load -n

script:
  - phpunit -c app

matrix:
  allow_failures:
    - php: nightly # Allow failures till stable release.
    - php: hhvm # Dropping hhvm support for now. Can't determine if failures are correct.
    - php: hhvm-nightly # hhvm-nightly currently chokes on composer installation
