language: php
sudo: false

php:
  - 5.6
  - 7.0
  - nightly
  - hhvm

env:
  global:
    - SYMFONY_ENV=test
    - SYMFONY__TEST_DATABASE_HOST=127.0.0.1
    - SYMFONY__TEST_DATABASE_NAME=clastic_test
    - SYMFONY__TEST_DATABASE_USER=travis
    - SYMFONY__TEST_DATABASE_PASSWORD=""

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - mysql -e 'create database clastic_test;'
  - composer self-update
  - composer install --prefer-dist --no-interaction $COMPOSER_FLAGS
  - php ./bin/console assets:install
  - php ./bin/console doctrine:schema:drop --force
  - php ./bin/console doctrine:schema:create
  - php ./bin/console doctrine:fixtures:load -n

script:
  - php ./vendor/bin/phpunit

matrix:
  allow_failures:
    - php: nightly # Allow failures till stable release.
