<?php

namespace Clastic\AliasBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AliasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AliasRepository extends EntityRepository
{
}
