<?php

namespace Clastic\AliasBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AliasPatternRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AliasPatternRepository extends EntityRepository
{
}
