Clastic\AliasBundle\Entity\Alias:
    type: entity
    table: null
    repositoryClass: Clastic\AliasBundle\Entity\AliasRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        alias:
            type: string
            length: 255
        path:
            type: string
            length: 255
    lifecycleCallbacks: {  }
