clastic_backoffice_dashboard:
    path:     /
    defaults: { _controller: ClasticBackofficeBundle:Dashboard:index }

clastic_backoffice_node:
    pattern:   /{type}
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: clastic_backoffice_list
        permanent: true

clastic_backoffice_list:
    path:     /{type}/list
    defaults: { _controller: ClasticBackofficeBundle:Node:list }

clastic_backoffice_form:
    path:     /{type}/edit/{nodeId}
    defaults: { _controller: ClasticBackofficeBundle:Node:form, nodeId: ~ }

clastic_backoffice_node_delete:
    path:     /{type}/delete/{nodeId}
    defaults: { _controller: ClasticBackofficeBundle:Node:delete }
