clastic_backoffice_dashboard:
    path:     /
    defaults: { _controller: ClasticBackofficeBundle:Dashboard:index }

clastic_backoffice_list:
    path:     /{type}/list
    defaults: { _controller: ClasticBackofficeBundle:Node:list }

clastic_backoffice_form:
    path:     /{type}/edit/{node_id}
    defaults: { _controller: ClasticBackofficeBundle:Node:form, node_id: ~ }
