services:
    clastic.backoffice.type.tabs:
        class: Clastic\BackofficeBundle\Form\Type\TabsType
        tags:
            - { name: form.type, alias: tabs }
    clastic.backoffice.type.tabs_tab:
        class: Clastic\BackofficeBundle\Form\Type\TabsTabType
        tags:
            - { name: form.type, alias: tabs_tab }
    clastic.backoffice.type.tabs_tab_actions:
        class: Clastic\BackofficeBundle\Form\Type\TabsTabActionsType
        tags:
            - { name: form.type, alias: tabs_tab_actions }
