#parameters:
##    router.options.matcher_class: Clastic\CoreBundle\Routing\UrlMatcher
#    router.class: Clastic\CoreBundle\Routing\Router

services:
  clastic.module_manager:
    class: Clastic\CoreBundle\Module\ModuleManager

#    clastic.kernel.listener.routing:
#        class: Clastic\CoreBundle\Routing\RouterListener
#        calls:
#          - [setMatcher, ["@clastic.url_matcher"]]
#        tags:
#            - { name: kernel.event_subscriber }

#    clastic.url_matcher:
#        class: Clastic\CoreBundle\Routing\UrlMatcher
#        calls:
#          - [setContext, ["@router.request_context"]]
