<?php
/**
 * This file is part of the Backend package.
 *
 * (c) Dries De Peuter <dries@nousefreak.be>
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Clastic\CoreBundle\Routing;

use Symfony\Component\Routing\Matcher\Request;


/**
 * @author Dries De Peuter <dries@nousefreak.be>
 */
class UrlMatcher extends \Symfony\Component\Routing\Matcher\UrlMatcher
{
    public function matchRequest(Request $request)
    {
        var_dump($request);die;
        return parent::matchRequest(
          $request
        ); // TODO: Change the autogenerated stub
    }

    public function match($pathinfo)
    {
        var_dump($pathinfo);die;
        return parent::match($pathinfo); // TODO: Change the autogenerated stub
    }

}
 