<?php

namespace Clastic\NodeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NodePublicationRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NodePublicationRepository extends EntityRepository
{
}
