<?php

namespace Clastic\TextBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TextRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TextRepository extends EntityRepository
{
}
