<?php

namespace Clastic\MenuBundle\Entity;

use Gedmo\Tree\Entity\Repository\NestedTreeRepository;

/**
 * MenuItemRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuItemRepository extends NestedTreeRepository
{
}
